### ISSUE TITLE
Responsive column layout

### ISSUE THREAD

**Issue by jacobthemyth** [ATMartin/TIY-Homework#19]
# Responsive columns
## Description

Create a simple responsive column layout
### Learning Objectives

After completing this assignment, you should...
- Understand how to use a grid framework to create a responsive layout
- Write SCSS that conforms to a style guide
### Performance Objectives

After completing this assignment, you be able to effectively use
- SCSS
- Bourbon
- Neat
- scss-lint
### Deliverables
- A repo containing at least:
  - `index.html`
  - `main.scss`
### Requirements

See Additional Resources for images of the layouts.
- It should have a desktop layout for when the browser is greater than 840px
  wide.
- It should have a tablet layout when the browser is between 840px and 500px
- It should have a mobile layout when the browser is less than 500px.
- The elements should become smaller as the browser shrinks (see video gif)
- Use the orange color found in the image resources rather than the blue color
  in the screenshots.
### Reading
- http://sass-guidelin.es/#introduction
- https://github.com/necolas/idiomatic-css
- http://cssguidelin.es/#css-selectors
- http://cssguidelin.es/#specificity
- http://sass-guidelin.es/#syntax--formatting
### Screenshots
- [Desktop](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/blob/master/responsive-columns/desktop.png)
- [Table](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/blob/master/responsive-columns/tablet.png)
- [Mobile](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/blob/master/responsive-columns/mobile.png)
### Icons
- [Icons](https://github.com/TIY-GVL-FEE-2015-Jan/homework-resources/tree/master/responsive-columns/icons)

![](https://raw.githubusercontent.com/TIY-GVL-FEE-2015-Jan/homework-resources/master/responsive-columns/video.gif)

**Comment by ATMartin** [comment]
https://github.com/ATMartin/TIY-HW-06-NeatResponsive.git

**Comment by ATMartin** [comment]
The instructions said to use orange like the icons, but the icons are blue, so I stuck with. I have sipped the orange color & converted the images, though, so maybe tomorrow I'll try to make a a:active field to change colors on the page. Anyway. All done for now. Thanks!

**Comment by ATMartin** [comment]
The instructions said to use orange like the icons, but the icons are blue, so I stuck with. I have sipped the orange color & converted the images, though, so maybe tomorrow I'll try to make a a:active field to change colors on the page. Anyway. All done for now. Thanks!

**Comment by jacobthemyth** [comment]
@ATMartin I completely forgot to let you know that I changed the images to blue and that you could just use the blue ones, I hope you didn't spend too much time on that. I'm sorry about that.
